# Generated by Django 3.0 on 2020-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('types', models.CharField(max_length=30)),
                ('officeadd', models.CharField(max_length=50)),
                ('residenceadd', models.CharField(max_length=50)),
                ('joiningdate', models.DateField()),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
