# Generated by Django 3.0 on 2020-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0007_registration_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
